# Generated by Django 5.0 on 2023-12-22 06:44

import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(blank=True, default='0.5x0.5', editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='avator',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='hero_images', verbose_name='Portfolio Avator'),
        ),
    ]
