# Generated by Django 5.0 on 2023-12-22 07:32

import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_ppoi_alter_portfolio_avator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='ppoi',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='avator',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='portfolio/', verbose_name='Portfolio Avator'),
        ),
    ]
