# Generated by Django 5.0 on 2023-12-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_portfolio_ppoi_alter_portfolio_avator'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='facebook',
            field=models.URLField(blank=True, unique=True, verbose_name='Facebook Link'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='github',
            field=models.URLField(blank=True, unique=True, verbose_name='Github Link'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='linked_in',
            field=models.URLField(blank=True, unique=True, verbose_name='Linkedin'),
        ),
    ]
