# Generated by Django 5.0 on 2023-12-26 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_portfolio_facebook_portfolio_github_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='linked_in',
            new_name='linkedin',
        ),
    ]
